[package]
name = "next-dev"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "next-dev"
path = "src/main.rs"
bench = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
tokio_console = [
  "dep:console-subscriber",
  "tokio/tracing",
  "turbo-tasks/tokio_tracing",
]

[dependencies]
anyhow = "1.0.47"
clap = { version = "3.1.3", features = ["derive"] }
console-subscriber = { version = "0.1.6", optional = true }
json = "0.12.4"
mime = "0.3.16"
serde = "1.0.136"
tokio = { version = "1.11.0", features = ["full"] }
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbo-tasks-memory = { path = "../turbo-tasks-memory" }
turbopack = { path = "../turbopack" }
turbopack-cli-utils = { path = "../turbopack-cli-utils" }
turbopack-core = { path = "../turbopack-core" }
turbopack-dev-server = { path = "../turbopack-dev-server" }
webbrowser = "0.7.1"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
